config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  resources :users
  resources :sessions
  resources :events
  resources :user_events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :user_events
    has_many :users_attending, :through => :user_events, source: :user

    validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, inverse_of: :creator
    has_many :user_events
    has_many :events_booked, :through => :user_events, source: :event

    validates :username, uniqueness: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private

    def require_login
        unless current_user
            redirect_to root_path
        end
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login

    def new
        @event = Event.new
    end

    def show
        @event = Event.find(params[:id])
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save!
            redirect_to root_path
        else
            render :new
        end
    end

    private

    def event_params
        params.require(:event).permit(:date, :description, :name, :user_id)
    end
end

#Troubleshoot why events won't save

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_username(params[:username])
        if user
            session[:user_id] = user.id
            redirect_to users_path
        else
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
    def create
     event = Event.find(params[:id])  
     user_event = UserEvent.new(event_id: event.id, user_id: current_user.id) 
    
     if user_event.save
        redirect_to root_path
     else 
        render :new
     end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def index
        @users = User.all
        @events = Event.all
    end

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:notice] = 'Login attempt failed.'
            redirect_to root_path
        else
            flash[:notice] = 'Login attempt failed.'
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name%>
    <%= form.label :description, "Description:" %>
    <%= form.text_field :description%>
    <%= form.label :date, "Date:" %>
    <%= form.date_select :date%>
    <%= form.submit "Submit" %>
    <% end %>

app/views/events/new.html.erb
<h1> Make a new event </h1>

<%= render 'form', event: @event %>

<%= link_to "Home", root_path %>

app/views/events/show.html.erb
<h1> Event information: </h1>

<ul>
    <li>Name: <%= @event.name  %></li>
    <li>Description: <%= @event.description  %></li>
    <li>Date: <%= @event.date %></li>
    <li>Creator: <%= @event.creator.username %></li>
</ul>

<h2> List of attendees: </h2>
    <ul>
    <% @event.users_attending.each do |user| %>
        <li><%= user.username %></li>
    <% end %>
    </ul>

<%= link_to "Sign up for this party", "/user_events?id=#{@event.id}", method: "post" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationsProjTop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if current_user %>
    <h1> Current user: <%= current_user.username %> </h1>
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2> Make a new event with this user: </h2>

<%= link_to "New event", new_event_path %>

<h2> List of users: </h2>

<ul>
 <% @users.each do |user| %>
    <li>
     <%= link_to user.username, user %>
    </li>
    <% end %>
</ul>

<h2> List of events: </h2>
<ul>
 <% @events.each do |event| %>
    <li>
     <%= link_to event.name, event %>
    </li>
    <% end %>
</ul>

<h2> Make a new user: </h2>

<%= link_to "Add a new user", new_user_path %>

app/views/users/new.html.erb
<h1> Make a new user </h1>

<%= form_with model: @user, method: :post do |form| %>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username%>
    <%= form.submit "Submit" %>
    <% end %>

<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<h2> Name of this user: <%= @user.username %> </h2>

<h2> List of events created by <%= @user.username %>: </h2>
<ul>
<% @user.events.each do |event| %>
    <li>
        <%= link_to event.name, event_path(event.id) %>
    </li>
    <% end %>
</ul>

<h2> List of events attended by <%= @user.username %>: </h2> 

<ul>
    <% @user.events_booked.each do |event| %>
        <li>
            <%= link_to event.name, event_path(event.id) %>
        </li>
    <% end %>
</ul>

<%= link_to "Home", root_path %>